config/routes.rb
Pennapp::Application.routes.draw do

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  resources :lectures do
    resources :notes do
      collection do
        get 'related'
      end
    end
  end

  match 'twilio/process_sms' => 'twilio#process_sms'
  match 'twilio/process_call' => 'twilio#process_call'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  
  validates :title, :presence => true, :length => {:minimum => 2}
  
  attr_accessible :title

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_filter :user_signed_in?

  def index
    @lectures = current_user.lectures.all(:order => 'created_at DESC')
  
    if params[:phone_number]
      current_user.phone_number = params[:phone_number]
      current_user.save
      flash.now[:alert] = "<strong>You've registered your phone number with Notable!</strong> You can now take notes via SMS to <strong>(484) 685-4865</strong> and they'll be added to your most recent lecture. To start a new note, send a text with the word 'start', followed by the title of your lecture."
    end
  end

  def new
    @lecture = current_user.lectures.new
  end

  def create
    @lecture = current_user.lectures.new(params[:lecture])
    if @lecture.save
      flash[:alert] = "The lecture has been created."
      redirect_to lectures_path
    else
      flash.now[:alert] = "There were errors creating your set."
      render :action => :new
    end
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/index.html.erb
<style type="text/css">
.lecture {
  padding: 20px;
  border-bottom: 1px solid #999;
}
.lecture a {
  font-size: 150%;
  font-weight: bold;
}
</style>

<div class="row">
  <% if !current_user.phone_number %>
    <div class="span3">
      <h3>Hey there!</h3>
  		<p><strong>Enter your phone number</strong> below to take notes from your phone!</p>
      <%= form_tag(lectures_path, :method => 'GET') do %>
  			<%= text_field_tag :phone_number, current_user.phone_number, :placeholder => '(212) 555-1212' %>
  			<%= submit_tag 'Save', :class => 'btn btn-success' %>
  		<% end %>
    </div>
  <% end %>

	<div class="span<%= current_user.phone_number ? 12 : 9 %>">
    <div class="page-header">
      <h1>Your Lectures</h1>
    </div>
    <%= link_to '<i class="icon-plus"></i> New lecture'.html_safe, new_lecture_path, :class => 'btn' %>
    <% for lecture in @lectures %>
      <div class="lecture">
        <%= link_to lecture.title, lecture_path(lecture)%>
        <div class="details"><%= pluralize lecture.notes.count, 'note' %>, created <%= time_ago_in_words lecture.created_at %> ago</div>
      </div>
    <% end %>

  </div>
</div>

app/views/lectures/new.html.erb
<div class="row">
  <div class="span12">
      <div class="page-header">
        <h1>New Lecture</h1>
      </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= form_for @lecture do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, :style => 'width: 925px; font-size: 180%; padding: 12px' %>
      <button type="submit" class="btn btn-primary"><i class="icon-file icon-white"></i> Create</button>
    <% end %>
  </div>
</div>

app/views/lectures/show.html.erb
<style type="text/css">
.MathJax_Display {text-align: left !important;}
audio{width:940px;}
</style>

<script type="text/javascript"
   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script src="/js/notes.js"></script>
<%= javascript_tag "
window.lecture_notes_url = '#{lecture_notes_url(@lecture)}';
window.related_lecture_notes_url = '#{related_lecture_notes_url(@lecture)}';
" %>
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1><%= @lecture.title %></h1>
    </div>
    <% af = TwilioController.get_audio(@lecture.created_at.to_time,10,current_user) %>
    <% if af %>
      <%= javascript_tag "window.audio_timestamp = #{af[:start_time].to_i*1000};" %>
      <audio id='player' src="<%= af[:recording].mp3 %>" controls>
      	<p>Boo Hoo, no HTML5 Audio for you</p>
      </audio>
   	<% end %>
    <table id="notelog" class="table table-striped">
    <tr id="headerrow">
      <th><div class="btn-group">
        <button class="btn dropdown-toggle" 
          data-toggle="dropdown" 
          href="#"
        >All</button>
      <ul class="dropdown-menu">
        <li><a id="showall"
          data-toggle="dropdown" 
          href="#"
        ></i>All</a></li>
        <li><a id="showimportant"
          data-toggle="dropdown" 
          href="#"
        ><i class="icon-star"></i> Important</a></li>
        <li><a id="showconfusing"
          data-toggle="dropdown" 
          href="#"
        ><i class="icon-question-sign"></i> Confusing</a></li>
      </ul>
      </div></th>
      <th></th>
      <th style="width:80%"></th></tr>
    </table>
    <input id="noteinput" placeholder="Type your notes here and press enter..." type="text" style="width:925px;height:50px"></input>

    <br><br><br>
    <br><br><br>
    <br><br><br>

  </div>
</div>